import WritingContainer from '/Template/AHUT_China/COM/WritingContainer.js'

export default {
    components: {
        'writing-container': WritingContainer
    },
    template: `
    <writing-container>
        <h1>Human Practices</h1>
        <hr/>
        
        <h2>1.The Interview at Yushan Lake Park</h2>
        <img-fluid alt="Human_Practices_01" src="/resources/images/HumanPractices_01.jpg"></img-fluid>
        <img-fluid alt="Human_Practices_02" src="/resources/images/HumanPractices_02.jpg"></img-fluid>
        <p>As the number of deaths from cancer continues to rise, the team broke with tradition and the high cost of treating women with breast cancer through statistical analysis of their treatment options, instead of expensive targeted drugs, the team’s new product targets breast cancer with proteins secreted by probiotics. In 2021, we conducted interviews in Yushan Lake Park, Ma on shan, to find out what people knew about breast cancer and how to treat and treat it. Through our research, our team found that the understanding of breast cancer and its treatment is not deep, and there are many misunderstandings. For example: partial or dependent on certain health care products, no one in the family has had breast cancer, they certainly will not later, many young women believe that breast cancer only exists in menopausal women, can be cured after removal. Some families are not rich enough to give up cancer treatment, believing that having cancer is equivalent to having terminal illness.</p>
        <p>So we introduced people to the concept of breast cancer, characteristics, formation conditions and cancer prevention measures, and to correct people’s long-standing misconception, such as long-term use of hormone drugs and breast cancer has a direct relationship; Family history is not the main factor of breast cancer, no healthy living habits and healthy eating habits, as well as the lack of correct awareness of prevention is the fundamental measure leading to breast cancer; They were also shown the results of the latest Breast Cancer Survey: Breast Cancer is occurring at a younger age in women, with about 50 per cent of young women aged 20-30 suffering from breast hyperplasia. Although Hyperplasia of the breast is not breast cancer, but if its further development, it is very likely to become cancerous. In particular, our team has developed a program that targets breast cancer with probiotic secreted proteins, so that more people can be treated, rather than facing the cancer head on because of expensive medical bills, no more fear of cancer. </p>
        <p>Our Human Practice-yushan Lake Park interview activities are of great significance, both to promote the iGEM competition to the masses, and also introduced our AHUT-China team. At the same time, the event to more public understanding of breast cancer-related knowledge, encourage the public to check-up on time, actively cooperate with the hospital treatment, thus reducing the incidence rate.</p>

        <h2>2.Multi-channel propaganda (Wechat, friend circle, public account)</h2>
        <p>AHUT_China upgraded its WeChat public account in 2021. During the implementation of the project this year, more than 10 original articles have been published since the establishment of the team. This year , we actively carry out social practice through such an external publicity platf1orm to promote the iGEM contest and introduce our project.</p>
        <p>After human practice, the AHUT-China team will promptly write a summary and translate it into English, published on its Wechat public account, Instagram account, and Twitter account.</p>
        <p>The office account of Anhui University of Technology's public account, iGEM, features three modules on Project Progress, Collaboration&Communication, and Popular Science Articles, which readers can consult.</p>
        <p>The Project Progress module includes the promotion team, the experiment process, and the Logo display. Our articles are regularly reported and updated weekly. In addition, the team holds regular meetings,from the 2021-3-15 weekly to 2021-10-10.</p>
        <p>The popular Science Articles module focuses on synthetic biology popular science. It promotes the International Genetically Engineered Machine Competition (iGEM), held annually by the Massachusetts Institute of Technology (MIT) since 2005, and is the highest international academic competition in synthetic biology. Furthermore, all the information is relevant to our team's experiments.</p>
        <p>The iGEM public account of Anhui University of Technology (AHUT) is aimed at schools and society, where Wechat users can access iGEM information. Thus, we can raise awareness of the International Genetically Engineered Machine Competition (iGEM) and create a good image of the AHUT_China team.At the same time, it also made a great contribution to the promotion of our project.</p>
        
        <h2>3.Social survey</h2>
        <p>In September, our team conducted a social survey of "how much I know about malignant tumors" in several elderly activity centers.</p>
        <p>The questionnaire includes:</p>
        <p>(1) What Age do you think breast cancer will occur?</p> 
        <p>(2) what do you know about breast cancer treatment?</p> 
        <p>(3)Do you think there is a high cure rate for breast cancer at this stage?</p> 
        <p>(4)Do you know what lifestyle habits/lifestyles can reduce the incidence of breast cancer?</p>
        <p>About 65% of people gave all the answers, but most were unclear about specific treatments for malignant tumors and ways to reduce their incidence. The analysis of the results of the questionnaire shows that the majority of the people still maintain the traditional view of cancer, which also encourages us to actively carry out large-scale propaganda work of malignant tumors, popularize preventive measures of malignant tumors, and reduce the incidence rate. Through this campaign, we will awaken the public’s inner awareness of the fight against cancer, calling for people to look at cancer positively, believe that modern medicine is constantly improving, treatment methods are constantly improving. And introduced people to the project our team was working on.</p>
        <img-fluid alt="Human_Practices_03" src="/resources/images/HumanPractices_03.jpg"></img-fluid>
        <img-fluid alt="Human_Practices_04" src="/resources/images/HumanPractices_04.jpg"></img-fluid>
        <img-fluid alt="Human_Practices_05" src="/resources/images/HumanPractices_05.jpg"></img-fluid>

        <h2>4.Love life and be optimistic</h2>
        <p>The theme of the 2021 is “Healthy Chinese health home-care for life, scientific prevention of Cancer”, “Light the way to fight cancer, help a healthy China”. Since 2010, China’s cancer incidence and mortality rate has been rising, the National Cancer Center recently released the latest data show that China’s cancer new growth rate of 3% , accounting for a quarter of the world’s new cancer cases.</p> 
        <p>Many people in our country lose their lives every year because of cancer. It has brought harm and burden to many families. Mental Health of cancer patients is very important. Some patients were diagnosed with cancer, talk about “Cancer”color change, more depressed, often feel worried. The emergence of these phenomena, the treatment is very adverse. Therefore, we should give patients psychological comfort, encourage them to fight against cancer for a long time, and actively cooperate with doctors to carry out standard treatment.</p> 
        <p>In the means of cancer prevention, besides following the basic principles of reasonable diet, moderate exercise, quitting smoking and limiting alcohol, and keeping healthy mentality, proper external intervention is also an effective means of preventing tumor diseases. The young healthy immune cells stored by high-tech means can effectively prevent the occurrence of tumor diseases when the immune function of human body is low and tumors are high.</p>
        <p>In response to the theme of the National Cancer Prevention Publicity, we launched the “Care for cancer patients, start from the heart”campaign through the wechat public account. Through various forms such as letter writing, painting and message writing, we will encourage cancer patients to speak out. Once the event was launched, it received an enthusiastic response.</p>

        <h2 id="gold">5.Our discussion with the AHUT Industrial Robotics Competition team</h2>
        <img-fluid alt="Human_Practices_06" src="/resources/images/HumanPractices_06.jpg"></img-fluid>
        <img-fluid alt="Human_Practices_07" src="/resources/images/HumanPractices_07.jpg"></img-fluid>
        <p>We discuss the guiding significance of industrial robots to automatic assembly line production to speed up the drug R & D cycle.</p>

        <h2>6.Field investigation in the oncology department of Ma'anshan People's Hospital</h2> 
        <p>The team members went to the Oncology Department of Ma'anshan People's Hospital for field investigation</p>
        <img-fluid alt="Human_Practices_08" src="/resources/images/HumanPractices_08.jpg"></img-fluid>
        <img-fluid alt="Human_Practices_09" src="/resources/images/HumanPractices_09.png"></img-fluid>
        <p>In order to understand the specific treatment process and treatment drugs for malignant tumors, our team contacted the oncology staff of Ma'anshan People's Hospital in August. On the premise of personal protection and not interrupting the regular treatment of the medical staff, we witnessed how they work with tumors.</p>
        <p>A malignant tumor is one of the primary diseases that harm human health. The treatment of tumors is the comprehensive application of surgery, radiotherapy, chemotherapy, interventional therapy, and traditional Chinese Medicine Treatment therapy.At present, the most commonly used biological treatment in clinical practice is trastuzumab injection. For breast cancer patients whose chemotherapy is ineffective, this method can achieve a certain therapeutic effect. Breast cancer patients can also consider using traditional Chinese medicine for treatment, but this method needs to be combined with other methods such as surgery to achieve the purpose of strengthening the body and eliminating evil. Through traditional Chinese medicine treatment, it can effectively enhance the body's anti-cancer ability and reduce the side effects of other treatments.</p>
        <p>Meanwhile, we understand that all current traditional cancer therapies have large side effects, and it will attack normal cells indiscriminately and we understand that the side effects of cancer treatment can sometimes be more harmful to the body than cancer itself because when drugs are used, the side effects can cause significant damage to normal tissue cells. In addition, while the patient holds a low tolerance to the effects and an abnormal immune system due to the disease, the patient's immune function will further decline with the drug injury. So, the patient is confronting huge risks. This has also brought great inspiration to our team's research. After research, it has been found that some bacteria have the function of targeting breast cancer cells and inhibiting their growth. Therefore, we plan to use engineered bacteria to treat breast cancer, and finally decided to take targeted treatment of breast cancer by secreting proteins from probiotics.</p>
        
        <h2>7.An exclusive interview with Dr. Jufen Yan</h2> 
        <img-fluid alt="Human_Practices_10" src="/resources/images/HumanPractices_10.jpg"></img-fluid>
        <p>During the experiment, we still had questions about the drug treatment of malignant tumors. Therefore, we made an exclusive interview with Dr. Jufen Yan , an expert in microorganisms and drugs. " At present, there is no good treatment for malignant tumors, and some chemical drugs and radiotherapy have serious side effects, for which we need some new treatments. In particular, some targeted therapies to reduce the generation of drug side effects, "she said. After hearing our introduction to the project, she praised that our project is novel and can provide new ideas for the treatment of malignant tumors. At the same time, she also explained to us the drug R & D and clinical research in detail : A new drug can be submitted to the regulatory authorities for a new drug application only if it completes all three stages clinical trials and analyzes all the information and data, and the safety and efficacy of the drug is demonstrated. A new drug sometimes takes over a dozen years.</p>
        <p>Dr. Jufen Yan 's words have given us great inspiration, the doctor affirmed our research direction. Next, our team will further optimize our project and begin to adjust the progress of the experiment in order to get a better treatment effect.</p>
        
        <h2>8.Visit Ma'anshan Fengyuan Pharmaceutical Co. Ltd</h2>
        <p>Our team visited the local pharmaceutical company in Ma'anshan. Considering that the drug has been developed, it needs mass production to be genuinely applied to medical treatment. Therefore, our team decided to visit the local pharmaceutical factory to investigate whether our manufacturing process could be applied to mass production. We chose to visit Ma'anshan Fengyuan Pharmaceutical Co., Ltd. because of its exquisite pharmaceutical technology and complete equipment.</p>
        <p>In September, after repeated solicitation, we contacted the company and followed a member of the company to visit the pharmaceutical technology of the company under the condition of ensuring hygiene.</p>
        <p>During the visit, the commentator explained the use of the company's pharmaceutical equipment to us in detail and put forward helpful suggestions for the manufacturing process of their laboratory. In order to apply）the drugs developed by the laboratory for large-scale production, our team improved our drug development process to better meet the needs of mechanized social production. To this end, I would like to thank Ma'anshan Fengyuan pharmaceutical company for providing us with this opportunity.</p>
        <img-fluid alt="Human_Practices_11" src="/resources/images/HumanPractices_11.jpg"></img-fluid>
        <img-fluid alt="Human_Practices_12" src="/resources/images/HumanPractices_12.jpg"></img-fluid>
        <img-fluid alt="Human_Practices_13" src="/resources/images/HumanPractices_13.jpg"></img-fluid>
        <img-fluid alt="Human_Practices_14" src="/resources/images/HumanPractices_14.jpg"></img-fluid>
        
        <h2>9.Host the presentation</h2>
        <p>In order to propagate the iGEM competition and our project , and make medical knowledge widely available, we invited representatives from each class to a presentation session held in the conference room.</p>
        <p>In the meeting, our team presented the research project - novel targeted drugs against tumor cells, which has an excellent prospect for treating malignant tumors. At last, we explained the current common treatments for tumors and shared healthy diets. In daily life, students should live regularly, exercise moderately, and get enough sleep. More importantly, we should quit smoking and limit alcohol, avoid sugary drinks and limit the intake of high-quality and dense diets. The presentation allowed the students to understand more about tumors, not be afraid of them, and believe more in today's technology in scientific medical care.</p>
        <p>After the meeting, many students asked some detailed questions about the characteristics of malignant tumors. We also had clear communication and discussion about the knowledge related to the novel targeted drugs developed by our team. Therefore, it proved to be a successful decision for us to hold the presentation. I believe that through our propaganda, everyone will be deeply impressed by the idea of engineered bacteria to treat breast cancer, targeted high-efficiency treatment, and targeted action on cancer cells. It is also the active discussion after the meeting that made us more aware of the victory Cancer cells are the current medical pain point. We will make unremitting efforts to this end. At the same time, we will do our utmost to promote the knowledge of cancer prevention.</p>
        <img-fluid alt="Human_Practices_15" src="/resources/images/HumanPractices_15.jpg"></img-fluid>
        <img-fluid alt="Human_Practices_16" src="/resources/images/HumanPractices_16.jpg"></img-fluid>
    </writing-container>
    `
}